# Use zsh as the default shell
set-option -g default-shell "/usr/bin/zsh"

# Enable 256 color support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Enable mouse support
set -g mouse on

# Fix escape key delay
set -sg escape-time 0
